### ISSUE TITLE
codefuse in kubernetes Requirements

### ISSUE THREAD

**Issue by mautops** [codefuse-ai/codefuse-ide#16]
codefuse 运行在 k8s 中并导出连接地址和端口

哪位社区的同学在做这个，想参与进去一起玩下；

**Comment by hacke2** [comment]
see https://github.com/codefuse-ai/codefuse-ide/tree/0.7.0?tab=readme-ov-file#start-the-web-project-experimental

**Comment by hacke2** [comment]
https://github.com/codefuse-ai/codefuse-ide/pull/54
