### ISSUE TITLE
支持web

### ISSUE THREAD

**Issue by chenls** [codefuse-ai/codefuse-ide#2]
会支持web吗

**Comment by hacke2** [comment]
> 会支持web吗

这个仓库目前只是会专注于桌面版，Web 项目参考 https://github.com/opensumi/ide-startup/blob/main/src/browser/index.ts 再加一个入口

**Comment by chenls** [comment]
您好！您的来信已收悉，我将尽快处理！谢谢！

**Comment by hacke2** [comment]
@chenls 已经支持了 https://github.com/codefuse-ai/codefuse-ide/tree/0.7.0?tab=readme-ov-file#start-the-web-project-experimental

**Comment by hacke2** [comment]
https://github.com/codefuse-ai/codefuse-ide/pull/54
