### ISSUE TITLE
CodeFuse IDE Support Web IDE

### ISSUE THREAD

**Issue by hacke2** [codefuse-ai/codefuse-ide#32]
CodeFuse IDE was initially positioned to focus on Desktop IDE + AI scenarios, but many partners in the community want to provide Web IDE to meet their internal Cloud IDE scenarios, so they can utilize the separation of the entrance, i.e., the construction method, and transform CodeFuse IDE to support Web IDE at the same time. the underlying framework of OpenSumi supports the construction of a dual-end IDE see https://github.com/opensumi/ide-startup .

**Comment by hacke2** [comment]
Related #16

**Comment by LofiSu** [comment]
这个的意思是opensumi也支持ai插件吗？

**Comment by LofiSu** [comment]
还是说要重新写个web项目？

**Comment by hacke2** [comment]
@LofiSu CodeFuse IDE 目前只支持桌面端，对这个项目进行改造，也可以启一个 Web IDE 形态

**Comment by LofiSu** [comment]
有什么提示吗

**Comment by hacke2** [comment]
@LofiSu 有社区同学已经提 PR 了，可以参考一下，你对 CodeFuse编码挑战季 感兴趣可以看看其他题目~

**Comment by hacke2** [comment]
cc @eedpublic

**Comment by eedpublic** [comment]
已完成
