### ISSUE TITLE
通过最新发布的0.6.4版本的Windows安装包，安装完成后无法打开

### ISSUE THREAD

**Issue by gaoshuaihui** [codefuse-ai/codefuse-ide#40]
通过最新发布的0.6.4版本的Windows安装包，安装完成后无法打开。
不过下载0.6.2版本的Windows安装包，安装完成后可以打开。同时通过安装后的0.6.2的ide，内部提示更新安装成0.6.4的方式，可以正常打开ide。
![安装页面](https://github.com/user-attachments/assets/bac889f8-9413-4a83-8cd3-fcbc3687e7a5)
![更新提示](https://github.com/user-attachments/assets/0fef1a4e-2493-4456-b62b-8f69239dbe75)

**Comment by lianeng0** [comment]
我也遇到，0.6.4安装完后打开直接闪退，系统是win10 x64

**Comment by hacke2** [comment]
我们看一下 Windows 上的问题，在 0.7 版本解决

**Comment by hacke2** [comment]
已修复
