### ISSUE TITLE
连接远程服务器

### ISSUE THREAD

**Issue by klykq111** [codefuse-ai/codefuse-ide#48]
目前的codefuse-ide能够像vscode一样连接远程服务器吗？

**Comment by hacke2** [comment]
目前还不支持类似 VS Code Remote 的方式连接，对于远程连接有需求目前可以通过 Web IDE 方式连进去，等 #54 合并

**Comment by hacke2** [comment]
除了上述 Web 的方式，OpenSumi 本身支持了一种基于 WebSocket 的简单 Remote 方式，参考 https://github.com/opensumi/core/blob/a6234eb1f5ddd2bc1f65f62752b42d44e442d723/packages/core-browser/src/react-providers/config-provider.tsx#L243
```ts
   /**
   * 指定当前是否通过 remote 模式连接到远程的 Server 端
   * 这将影响 Terminal 与 Extension 模块与子进程的连接方式
   */
  isRemote?: boolean;

```

在 Client 端开启 isRemote，然后使用 wsPath 链接远端的 Server
