### ISSUE TITLE
VS插件兼容问题

### ISSUE THREAD

**Issue by itcloudy** [codefuse-ai/codefuse-ide#61]
现象：
我们在vsode上的插件，可以正常运行，插件的页面能出来
<img width="1511" alt="截屏2024-11-29 15 09 58" src="https://github.com/user-attachments/assets/c4111dc3-8b70-479f-8c2b-c70ec2d60df4">
迁移到codefuse上无法正常工作
<img width="1507" alt="截屏2024-11-29 15 11 29" src="https://github.com/user-attachments/assets/e2cda39b-1173-4843-8990-e5a82cb3b42a">
为了验证该问题我们使用codefuse和vs code同时打开一个工程，并且同时安装了drawio，vs code上能正常显示drawio页面，并能绘图，codefuse没有任何内容，
<img width="1512" alt="截屏2024-11-29 15 13 49" src="https://github.com/user-attachments/assets/f25002ba-4524-40eb-975c-dd793955e356">
opensumi文档中提到版本兼容，没看到open粟米具体版本跟vscode插件api的兼容表
<img width="1510" alt="截屏2024-11-29 15 16 43" src="https://github.com/user-attachments/assets/e67631fd-b2fe-4764-a66d-8dca39406693">

**Comment by hacke2** [comment]
对应插件或者可以复现的最小示例贴一下

**Comment by itcloudy** [comment]
> 对应插件或者可以复现的最小示例贴一下

[qsemos-embedded.ide-plugin-1.0.0.vsix.zip](https://github.com/user-attachments/files/17976318/qsemos-embedded.ide-plugin-1.0.0.vsix.zip)

**Comment by hacke2** [comment]
@itcloudy 看了下插件，插件写法不是非常标准，有两点问题：

1. 没有激活事件
```json
 "activationEvents": [],
```
activationEvents 事件里必须写一个值，参考 https://code.visualstudio.com/api/references/activation-events 写一个值，例

```json
 "activationEvents": ["*"],
```
2. 入口文件路径有问题
```
"main": "/views/extension.js",
```

请按照相对路径修改，例
```
"main": "views/extension.js",
```

以上两点修改后：

![image](https://github.com/user-attachments/assets/2c5f88ab-7141-4853-89a5-a13b6e437259)

**Comment by kim-5085** [comment]
[soft-realtime-1.0.78.zip](https://github.com/user-attachments/files/18032152/soft-realtime-1.0.78.zip)
新上传了一个插件，这个插件应该是没有这类问题的（1、没有激活事件。2、入口文件路径有问题。），但是也是无法打开
